# Generated by Django 5.0 on 2024-02-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='uploads/images')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('on_offer', models.BooleanField(default=False)),
            ],
        ),
    ]
